spring.application.name=pedidos

spring.datasource.url=jdbc:postgresql://localhost:5555/icompraspedidos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

icompras.pedidos.clients.produtos.url=http://localhost:8081/produtos
icompras.pedidos.clients.clientes.url=http://localhost:8082/clientes
icompras.config.kafka.server-url=http://localhost:29092
icompras.config.kafka.topics.pedidos-pagos=icompras.pedidos-pagos
icompras.config.kafka.topics.pedidos-faturados=icompras.pedidos-faturados
icompras.config.kafka.topics.pedidos-enviados=icompras.pedidos-enviados