spring.application.name=logistica

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=icompras-logistica
spring.kafka.consumer.auto-offset-reset=earliest

icompras.config.kafka.topics.pedidos-faturados=icompras.pedidos-faturados
icompras.config.kafka.topics.pedidos-enviados=icompras.pedidos-enviados

server.port=8084