spring.application.name=faturamento

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=icompras-faturamento
spring.kafka.consumer.auto-offset-reset=earliest

icompras.config.kafka.topics.pedidos-pagos=icompras.pedidos-pagos
icompras.config.kafka.topics.pedidos-faturados=icompras.pedidos-faturados

server.port: 8083

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=icompras.faturas